BUILD_BINARY=1 \
BUILD_TEST=1 \
BUILD_MOBILE_TEST=1 \
ANDROID_ABI=arm64-v8a \
  ./scripts/build_android.sh \
  -DANDROID_CCACHE=$(which ccache) \
  -DANDROID_DEBUG_SYMBOLS=ON \
  -DBUILD_BINARY=ON \
  -DBUILD_TEST=ON \
  -DBUILD_MOBILE_TEST=ON \
  -DUSE_VULKAN=ON
